site_name: Welcome to Shi-Wei Zhao's page
site_url: https://example.com/
nav:
    - Shi-Wei Zhao: index.md
    - Blog:
      - 2023:
        - 20230716_First blog: Blog/20230716_first_blog_in_page.md
    - Biology:
      - Evolution: Biology/Biology.md
    - Programming:
      - R:
        - Foundation: Programming/R_.md
      - Python:
        - Foundation: Programming/Python_.md
    - Omics:
      - Genomics: Omics/Genomics.md
      - Pan Genomics: Omics/PanGenomics.md
    - Deep Learning:
      - Foundation: DeepLearning/Foundation.md
      - Machine Learning: DeepLearning/MachineLearning.md
      - Deep Learning: DeepLearning/DeepLearning.md
    - About: about.md
theme: windmill
